version: "3"
services:
  postgres:
    image: postgres:16rc1-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./DB/database:/var/lib/postgresql/data
      - ./DB/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
        - backend
    restart: always
    
  python:
    build: Backend
    container_name: flask
    volumes:
      - ./Backend/scripts:/home/scripts
    entrypoint: ["flask","--app", "main","run", "--host=0.0.0.0"]
    ports:
      - 5000:5000
    networks:
        - backend
        - frontend
    restart: always

  nginx:
    image: nginx:mainline-alpine3.18
    container_name: nginx
    volumes:
      - ./Frontend/www:/usr/share/nginx/html
    ports:
      - 8888:80
    networks:
        - frontend
    restart: always

networks:
  frontend:
  backend:
